name: build rootfs

on:
  push:
    branches: [ 'master', 'dev' ]
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  build:
    name: Build tar file
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    env:
      GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run build.sh
        run: |
          sudo bash build.sh ${{ matrix.arch }}

      - name: Read version
        id: read_version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Upload file to release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ env.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.VERSION }}-${{ matrix.arch }}"
          prerelease: true
          title: "v${{ env.VERSION }}-${{ matrix.arch }}"
          files: |
            deepin-rootfs-${{ matrix.arch }}.tar.gz
